# Generated by Django 4.2 on 2023-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bar_food',
            field=models.BooleanField(default=False),
        ),
    ]
