# Generated by Django 4.2 on 2023-04-30 19:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_category_bar_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=70)),
                ('meal_description', models.TextField()),
                ('meal_image1', models.ImageField(upload_to='meal_images/')),
                ('meal_image2', models.ImageField(upload_to='meal_images/')),
                ('meal_image3', models.ImageField(upload_to='meal_images/')),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_hot', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.category')),
            ],
        ),
    ]
