# Generated by Django 4.2 on 2023-04-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_image2',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_image3',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.cart')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.meal')),
            ],
        ),
    ]
