# Generated by Django 4.2 on 2023-05-10 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo_text', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_image', models.ImageField(upload_to='logo/')),
                ('main', models.BooleanField(default=True)),
            ],
        ),
    ]
